name: Build

on:
  workflow_call:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: StaticCheck
        run: make staticcheck

      - name: Lint
        run: make lint

      - name: Vet
        run: make vet

      - name: Verify
        run: make verify

      - name: Test
        run: make test

      - name: Build
        run: make release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: github.event_name != 'pull_request'
        with:
          name: build-output
          path: _output/
          if-no-files-found: error
