name: Prerelease

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  prerelease:
    name: Prerelease
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-output

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: prerelease
          prerelease: true
          files: "*"
